# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tyk_root
      MONGO_INITDB_ROOT_PASSWORD: v5T4p39LY9BczSPqMeW3McqwK6pWsEwBVM7rmWkCpeUU44sW

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: tyk_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 9hV7AYcDdj7PdveDzTn5fvPckZZ8MGTc

# docker-compose -f tyk_mondo.yml up
# or
# docker stack deploy -c tyk_mongo.yml mongo
